# Generated by Django 4.1.5 on 2023-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_newproductmodel_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproductmodel',
            name='color',
        ),
        migrations.AddField(
            model_name='newproductmodel',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='new_colors', to='products.prcolormodel', verbose_name='color'),
        ),
    ]
