# Generated by Django 4.1.5 on 2023-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_newproductmodel_brand_newproductmodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmedia',
            name='i',
        ),
        migrations.AlterField(
            model_name='allmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='all_images'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
