# Generated by Django 4.1.5 on 2023-05-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_allmedia_i_alter_allmedia_image_delete_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmedia',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='all_images'),
        ),
    ]
