# Generated by Django 4.1.5 on 2024-06-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_newproductmodel_is_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductmodel',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='products.productattributevalue', verbose_name='attributes'),
        ),
    ]
