# Generated by Django 4.1.5 on 2023-04-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='full_name')),
                ('phone_number', models.CharField(max_length=100, verbose_name='phone_number')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('town', models.CharField(max_length=100, verbose_name='town')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('comment', models.TextField(verbose_name='comment')),
                ('PAY_STATUS', models.BooleanField(default=False, verbose_name='PAY_STATUS')),
                ('NAXT_STATUS', models.BooleanField(default=False, verbose_name='NAXT_STATUS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('generate_link', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cart', models.ManyToManyField(blank=True, to='cart.cartitem', verbose_name='cart')),
            ],
        ),
    ]
