# Generated by Django 4.1.5 on 2023-04-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'Checkout', 'verbose_name_plural': 'Checkout'},
        ),
    ]
