# Generated by Django 4.1.5 on 2023-04-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_checkout_charge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='charge_status',
            field=models.CharField(blank=True, choices=[('not-charged', 'Not charged'), ('pending', 'Pending'), ('partially-charged', 'Partially charged'), ('fully-charged', 'Fully charged'), ('partially-refunded', 'Partially refunded'), ('fully-refunded', 'Fully refunded'), ('refused', 'Refused'), ('cancelled', 'Cancelled')], max_length=20, null=True, verbose_name='charge_status'),
        ),
    ]
