# Generated by Django 4.1.5 on 2023-05-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='cart_status'),
        ),
    ]
