# Generated by Django 4.1.5 on 2023-05-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='title'),
        ),
    ]
