# Generated by Django 4.1.5 on 2023-05-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_map_phone_number_alter_map_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='region',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='region'),
        ),
    ]
